package ProjectManagementmodel.BC.VO;

import java.math.BigDecimal;

import java.util.Map;

import javax.servlet.http.HttpSession;

import oracle.adf.share.ADFContext;

import oracle.jbo.server.ViewObjectImpl;
import oracle.jbo.server.ViewRowSetImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Jan 27 14:49:30 IST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ProjectMasterViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ProjectMasterViewImpl() {
    }


    @Override
    public void prepareRowSetForQuery(ViewRowSetImpl viewRowSetImpl) {
        // TODO Implement this method
        Map session = ADFContext.getCurrent().getSessionScope();
        setMgrCode(new BigDecimal(session.get("userid").toString()));
        super.prepareRowSetForQuery(viewRowSetImpl);
    }

    /**
     * Returns the bind variable value for MgrCode.
     * @return bind variable value for MgrCode
     */
    public BigDecimal getMgrCode() {
        return (BigDecimal) getNamedWhereClauseParam("MgrCode");
    }

    /**
     * Sets <code>value</code> for bind variable MgrCode.
     * @param value value to bind as MgrCode
     */
    public void setMgrCode(BigDecimal value) {
        setNamedWhereClauseParam("MgrCode", value);
    }
}

