package ProjectManagementmodel.BC.EO;

import java.math.BigDecimal;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.SequenceImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Jan 27 15:32:17 IST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DependencyRequestsImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        ProjectCode,
        RequestId,
        DependencyId,
        DependencyDescription,
        ProgrammerCode,
        Status,
        ProjectMaster,
        Users,
        ProjectRequests;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int PROJECTCODE = AttributesEnum.ProjectCode.index();
    public static final int REQUESTID = AttributesEnum.RequestId.index();
    public static final int DEPENDENCYID = AttributesEnum.DependencyId.index();
    public static final int DEPENDENCYDESCRIPTION = AttributesEnum.DependencyDescription.index();
    public static final int PROGRAMMERCODE = AttributesEnum.ProgrammerCode.index();
    public static final int STATUS = AttributesEnum.Status.index();
    public static final int PROJECTMASTER = AttributesEnum.ProjectMaster.index();
    public static final int USERS = AttributesEnum.Users.index();
    public static final int PROJECTREQUESTS = AttributesEnum.ProjectRequests.index();

    /**
     * This is the default constructor (do not remove).
     */
    public DependencyRequestsImpl() {
    }

    /**
     * Gets the attribute value for ProjectCode, using the alias name ProjectCode.
     * @return the value of ProjectCode
     */
    public BigDecimal getProjectCode() {
        return (BigDecimal) getAttributeInternal(PROJECTCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ProjectCode.
     * @param value value to set the ProjectCode
     */
    public void setProjectCode(BigDecimal value) {
        setAttributeInternal(PROJECTCODE, value);
    }

    /**
     * Gets the attribute value for RequestId, using the alias name RequestId.
     * @return the value of RequestId
     */
    public BigDecimal getRequestId() {
        return (BigDecimal) getAttributeInternal(REQUESTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for RequestId.
     * @param value value to set the RequestId
     */
    public void setRequestId(BigDecimal value) {
        setAttributeInternal(REQUESTID, value);
    }

    /**
     * Gets the attribute value for DependencyId, using the alias name DependencyId.
     * @return the value of DependencyId
     */
    public BigDecimal getDependencyId() {
        return (BigDecimal) getAttributeInternal(DEPENDENCYID);
    }

    /**
     * Sets <code>value</code> as the attribute value for DependencyId.
     * @param value value to set the DependencyId
     */
    public void setDependencyId(BigDecimal value) {
        setAttributeInternal(DEPENDENCYID, value);
    }

    /**
     * Gets the attribute value for DependencyDescription, using the alias name DependencyDescription.
     * @return the value of DependencyDescription
     */
    public String getDependencyDescription() {
        return (String) getAttributeInternal(DEPENDENCYDESCRIPTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for DependencyDescription.
     * @param value value to set the DependencyDescription
     */
    public void setDependencyDescription(String value) {
        setAttributeInternal(DEPENDENCYDESCRIPTION, value);
    }

    /**
     * Gets the attribute value for ProgrammerCode, using the alias name ProgrammerCode.
     * @return the value of ProgrammerCode
     */
    public BigDecimal getProgrammerCode() {
        return (BigDecimal) getAttributeInternal(PROGRAMMERCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ProgrammerCode.
     * @param value value to set the ProgrammerCode
     */
    public void setProgrammerCode(BigDecimal value) {
        setAttributeInternal(PROGRAMMERCODE, value);
    }

    /**
     * Gets the attribute value for Status, using the alias name Status.
     * @return the value of Status
     */
    public String getStatus() {
        return (String) getAttributeInternal(STATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Status.
     * @param value value to set the Status
     */
    public void setStatus(String value) {
        setAttributeInternal(STATUS, value);
    }

    /**
     * @return the associated entity ProjectMasterImpl.
     */
    public ProjectMasterImpl getProjectMaster() {
        return (ProjectMasterImpl) getAttributeInternal(PROJECTMASTER);
    }

    /**
     * Sets <code>value</code> as the associated entity ProjectMasterImpl.
     */
    public void setProjectMaster(ProjectMasterImpl value) {
        setAttributeInternal(PROJECTMASTER, value);
    }

    /**
     * @return the associated entity UsersImpl.
     */
    public UsersImpl getUsers() {
        return (UsersImpl) getAttributeInternal(USERS);
    }

    /**
     * Sets <code>value</code> as the associated entity UsersImpl.
     */
    public void setUsers(UsersImpl value) {
        setAttributeInternal(USERS, value);
    }

    /**
     * @return the associated entity ProjectRequestsImpl.
     */
    public ProjectRequestsImpl getProjectRequests() {
        return (ProjectRequestsImpl) getAttributeInternal(PROJECTREQUESTS);
    }

    /**
     * Sets <code>value</code> as the associated entity ProjectRequestsImpl.
     */
    public void setProjectRequests(ProjectRequestsImpl value) {
        setAttributeInternal(PROJECTREQUESTS, value);
    }

    /**
     * @param dependencyId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(BigDecimal dependencyId) {
        return new Key(new Object[] { dependencyId });
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("ProjectManagementmodel.BC.EO.DependencyRequests");
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
    }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        
        if (operation == DML_INSERT){
            SequenceImpl s = new SequenceImpl("DEP_SEQ", getDBTransaction());
            BigDecimal cuser_seq = new BigDecimal(s.getSequenceNumber().toString());
            setDependencyId(cuser_seq);
            }
        super.doDML(operation, e);
    }
}

